#! /bin/bash

# get repository name
___repo_path="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
# name is the basename w/o version, unsafe replaced with _, and upper-case
___repo_name="$(
    basename "$___repo_path" | sed -e 's/[-.].*//g; s/[^A-Za-z0-9_]/_/g' |
    tr '[:lower:]' '[:upper:]'
)"
# make sure the repo name has at least some non-underscore characters
if [[ -z "${___repo_name//_}" ]]; then ___repo_name=REPO; fi

# show help
for arg in "$@"; do if [[ "$arg" == '--help' ]]; then
    printf 'Deactivate the environment for %s\n' "$___repo_name"
    printf '\nusage: . %q [--help]\n' "${BASH_SOURCE[0]}"
    printf '\narguemnt:\n'
    printf '  --help  print this message and quit w/o deactivating\n'
    printf '\nactions:\n'
    printf '  - removes $%s/bin and $%s/venv/bin from PATH\n' \
        "$___repo_name" "$___repo_name"
    printf '  - removes $%s/pylib from PYTHONPATH\n' "$___repo_name"
    printf '  - unsets %s and %s_* variables\n' "$___repo_name"  "$___repo_name"
    printf '  - unsets VIRTUAL_ENV from %s if applicable\n' "$___repo_name"
    unset ___repo_name ___repo_path
    # shellcheck disable=SC2317 # exit from either source or execution
    return 1 2>/dev/null || exit 1
fi; done

# make path removal function
___rm_path() {
    local name="$1" rm_path="$2" p path=''
    while IFS= read -d : -r p; do
        if [[ "$p" == "$rm_path" ]]; then continue; fi
        path+="$p:"
    done <<< "${!name}:"
    export "$name=${path%:}"
}

# remove from PATH, PYTHONPATH, and VIRTUAL_ENV
___rm_path PATH "$___repo_path/bin"
___rm_path PYTHONPATH "$___repo_path/pylib"
if [[ "$VIRTUAL_ENV" == "$___repo_path/venv" ]]; then
    ___rm_path PATH "$___repo_path/venv/bin"
    unset VIRTUAL_ENV
fi
unset -f ___rm_path
hash -r 2>/dev/null  # ensures PATH is re-searched, since we changed it

# remove repo variables
while IFS='=' read -r -d '' ___name ___value; do
    if [[ "$___name" == "$___repo_name"_* ]]; then
        unset "$___name"
    fi
done < <(env -0)
unset ___name ___value

# tell the user what we did
if [[ -t 1 ]]; then
    printf 'deactivated %s=%q\n' "$___repo_name" "${!___repo_name}"
fi
unset "$___repo_name" ___repo_name ___repo_path
